directories:
  output: dist_appx
  buildResources: build
appId: com.notesapp.desktop
productName: Refined Notes
files:
  - filter:
      - src/**/*
      - assets/**/*
      - package.json
win:
  target:
    - nsis
    - appx
  icon: assets/AppLogo.png
mac:
  target: dmg
  icon: assets/AppLogo.png
linux:
  target: AppImage
  icon: assets/AppLogo.png
electronVersion: 27.3.11
