name: Build Windows Appx (signed)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-appx:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Restore PFX from secret (base64)
        if: ${{ secrets.PFX_BASE64 != '' }}
        run: |
          echo Restoring PFX to runner
          $pfxPath = "${{ github.workspace }}\\build_cert.pfx"
          [System.IO.File]::WriteAllBytes($pfxPath, [System.Convert]::FromBase64String("${{ secrets.PFX_BASE64 }}"))
          Write-Output "PFX saved to $pfxPath"
          echo "::set-output name=pfx::$pfxPath"
        shell: powershell

      - name: Configure signing env
        if: ${{ secrets.PFX_BASE64 != '' }}
        run: |
          $pfxPath = "${{ github.workspace }}\\build_cert.pfx"
          echo "Setting CSC_LINK and CSC_KEY_PASSWORD"
          echo "##[set-env name=CSC_LINK]file:///$pfxPath"
          echo "##[set-env name=CSC_KEY_PASSWORD]${{ secrets.PFX_PASSWORD }}"
        shell: powershell

      - name: Build signed Appx
        env:
          CSC_LINK: ${{ format('file:///{0}', github.workspace) }}\build_cert.pfx
          CSC_KEY_PASSWORD: ${{ secrets.PFX_PASSWORD }}
        run: npm run build:appx

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: appx-artifacts
          path: dist_appx/**
