name: Build Windows Appx (signed)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-appx:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Skip PFX for unsigned build
        run: |
          Write-Host "Building unsigned Appx/MSIX for Partner Center submission (Microsoft will sign for Store distribution)."
        shell: powershell

      - name: Build Appx / MSIX
        run: |
          echo "Running electron-builder (appx)"
          npm run build:appx

      - name: List build output for debugging
        run: |
          echo "Contents of dist_appx:"
          if (Test-Path dist_appx) { dir -Recurse -Force dist_appx } else { echo "dist_appx missing" }
        shell: powershell

      - name: Upload Appx/MSIX artifact(s)
        uses: actions/upload-artifact@v4
        with:
          name: appx-artifacts
          path: |
            dist_appx/**/*.appx
            dist_appx/**/*.msix
            dist_appx/**/*AppxBundle*.msix
            dist_appx/**
